### ISSUE TITLE
What is the status of this crate vs odbc-rs?

### ISSUE THREAD

**Issue by jpastuszek** [pacman82/odbc-safe#14]
I would like to update odbc-iter crate, which is currently based on odbc-rs, but there are multiple issues with it. Now I am considering if odbc-safe is not a better target - looks more well typed and avoids some features duplication with odbc-iter as it is lower level.

Is this crate the main focus of development right now? Will odbc-rs continue to develop?

**Comment by pacman82** [comment]
I can not speak for the other maintainers, but since no one answered your question in six days.

At least I have stopped working on `odbc-safe` altogeher. Others are still maintaining it. Sadly for the use cases I had in mind (bulk insertions, and block reads) `odbc-safe` does not work from me. It is to low level, to provide both a safe and zero cost abstraction over odbc. The way `odbc` shares mutable buffers between writer and reader is hard to express safely in Rust typessystem.

I've only limited time to do Open Source work right now, but i am experimenting with `odbc-api`. Which is roughly the same abstraction level as `odbc-safe`. Yet does not aim to provide a complete safe abstraction, but only tries to be the foundation for higher level safe abstractions.

It's rather incomplete. So if you should just to use it, expect to drop down to `odbc-sys` frequently. You can look at `odbcsv` to see a small sample application using `odbc-api`. If I should find the time my plans are to take `odbc-api` at least far enough so I can implement an ODBC to Parquet tool.

**Comment by pacman82** [comment]
By now I feel `odbc-api` has the superiour design compared to the `odbc-safe` and `odbc` crates. I'll focus my efforts on reaching feature parity using `odbc-api`. In terms of querying data `odbc-api` might already be the best choice, since it has the best query performance (much, MUCH better than anything you can do with the other two crates right now), due to being able to query whole row sets in bulk rather than individual rows. However currently you require a custom and unsafe buffer implementation to do so. I'll plan to change this shortly.
