### ISSUE TITLE
Multi threading and asynchronous capabilities

### ISSUE THREAD

**Issue by brandonros** [pacman82/odbc-safe#8]
What's the status/progress on these features that are disclosed on the README as unsupported? What would it take to get these implemented?

**Comment by pacman82** [comment]
Hello, I want to wait a bit on the other contributers to react to #15 . Personally I wont add support for it within this crate. My current take on multithreading with ODBC can be seen here: https://docs.rs/odbc-api/0.10.1/odbc_api/struct.Connection.html#method.promote_to_send

In a nutshell, I leave the Connection without a `Send` or `Sync` implementation by default, but give users an `unsafe` option to opt in, if they know their drivers to be thread safe.

If you do not want to migrate from `odbc-safe` or `odbc` you can also do this using the `force-send-sync` crate. In that case please only use `Send` and not `Sync` even if you know your driver to be theard safe, because using `Sync` would also require a careful review of this crates code looking at ever `&self` and checking if it should not be `&mut self` instead.

**Comment by pacman82** [comment]
As of now, I do not see anyone adding support for Multithreading to this crate. I recommend switching to `odbc-api`.
